/*
 important*/
(function(c){var b=function(){};b.test=document.createElement("div");b.randomiseArray=function(a){var b=[],d=[],c;for(c=0;c<a;c++)b[c]=c;for(c=0;c<a;c++){var l=Math.round(Math.random()*(b.length-1));d[c]=b[l];b.splice(l,1)}return d};b.sortArray=function(a,b){var d,c=a.length,f=[];for(d=0;d<c;d++)f[d]=a[b[d]];return f};b.keysrt=function(a,b,d){var c=1;d&&(c=-1);return a.sort(function(a,d){var f=a[b],p=d[b];return c*(f<p?-1:f>p?1:0)})};b.keysrt2=function(a,b,d,c){var f=1;c&&(f=-1);return a.sort(function(a,
c){var p=a[b][d],A=c[b][d];return f*(p<A?-1:p>A?1:0)})};b.isEmpty=function(a){return 0==a.replace(/^\s+|\s+$/g,"").length};b.checkKey=function(a){return a.replace(/[^0-9a-zA-Z_-\s(),]/g,"")};b.stripSlashes=function(a){a=a.replace(/\\/g,"/");a=a.replace(/\\'/g,"'");a=a.replace(/\\"/g,'"');a=a.replace(/\\0/g,"\x00");return a=a.replace(/\\\\/g,"\\")};b.filterAllowedChars=function(a){var b=a.length,d="",c;for(c=0;c<b;c++){var l=a.charAt(c).toLowerCase();"\\"==l&&(l="/");var r=l.charCodeAt(0);if(97<=r&&
122>=r||48<=r&&57>=r||0<="_-".indexOf(l))d+=l}return d};b.selectText=function(a){var b=document;a=b.getElementById(a);if(b.body.createTextRange)b=b.body.createTextRange(),b.moveToElementText(a),b.select();else if(c.getSelection){var d=c.getSelection();b=b.createRange();b.selectNodeContents(a);d.removeAllRanges();d.addRange(b)}};b.getVideoFormat=function(){var a=document.createElement("video");if(a.canPlayType){if("probably"==a.canPlayType("video/mp4")||"maybe"==a.canPlayType("video/mp4"))var b=".mp4";
else if("probably"==a.canPlayType("video/ogg")||"maybe"==a.canPlayType("video/ogg"))b=".ogg";else if("probably"==a.canPlayType("video/webm")||"maybe"==a.canPlayType("video/webm"))b=".webm";return b}};b.videoSupport=function(){return!!document.createElement("video").canPlayType};b.canPlayVorbis=function(){var a=document.createElement("video");return!(!a.canPlayType||!a.canPlayType('video/ogg; codecs="theora, vorbis"').replace(/no/,""))};b.canPlayMp4=function(){var a=document.createElement("video");
return!(!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"').replace(/no/,""))};b.canPlayWebM=function(){var a=document.createElement("video");return!(!a.canPlayType||!a.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/no/,""))};b.audioSupport=function(){return!!document.createElement("audio").canPlayType};b.canPlayMp3=function(){var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/mpeg;").replace(/no/,""))};b.canPlayWav=function(){var a=
document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/wav;").replace(/no/,""))};b.canPlayAac=function(){var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/aac;").replace(/no/,""))};b.canPlayOgg=function(){var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,""))};b.volumeCanBeSet=function(){var a=document.createElement("audio");if(!a)return!1;a.volume=0;return 0==a.volume?!0:
!1};b.hasPointerEvent=function(){return!!c.navigator.msPointerEnabled};b.isMobile=function(){return b.hasPointerEvent&&1<navigator.msMaxTouchPoints?!0:/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};b.isMac=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("mac")};b.isWin=function(){return-1!=navigator.appVersion.toLowerCase().indexOf("win")};b.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};b.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};
b.isiPad=function(){return-1<navigator.userAgent.indexOf("iPad")};b.isiPhoneIpod=function(){var a=navigator.userAgent;return-1<a.indexOf("iPhone")||-1<a.indexOf("iPod")};b.isSafari=function(){return 0<Object.prototype.toString.call(c.HTMLElement).indexOf("Constructor")};b.isChrome=function(){var a=navigator.userAgent,b=!(0<Object.prototype.toString.call(c.HTMLElement).indexOf("Constructor"))&&"WebkitTransform"in document.documentElement.style;(-1<a.indexOf("iPhone")||-1<a.indexOf("iPod")||-1<a.indexOf("iPad"))&&
a.match("CriOS")&&(b=!0);return b};b.isOpera=function(){return!(!c.opera||!c.opera.version)};b.isIE=function(){var a=c.navigator.userAgent,b=a.indexOf("MSIE ");if(0<b)return parseInt(a.substring(b+5,a.indexOf(".",b)),10);if(0<a.indexOf("Trident/"))return b=a.indexOf("rv:"),parseInt(a.substring(b+3,a.indexOf(".",b)),10);b=a.indexOf("Edge/");return 0<b?parseInt(a.substring(b+5,a.indexOf(".",b)),10):!1};b.parseXML=function(a){if(c.ActiveXObject&&c.GetObject){var b=new ActiveXObject("Microsoft.XMLDOM");
b.loadXML(a);return b}if(c.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");throw Error("No XML parser available");};b.baseUrl=function(){return c.location.href.replace(c.location.hash,"")};b.protocol=function(){return c.location.protocol};b.qualifyURL=function(a){var b=document.createElement("a");b.href=a;return b.href};b.hasLocalStorage=function(){try{return"localStorage"in c&&null!==c.localStorage}catch(a){return!1}};b.validateEmail=function(a){return/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/.test(a)?
!0:!1};b.hasDownloadSupport=function(a){return"download"in document.createElement("a")};b.relativePath=function(a){return/^(?:[a-z]+:)?\/\//i.test(a)};b.getScrollOffsets=function(){if(null!=c.pageXOffset)return{x:c.pageXOffset,y:c.pageYOffset};if("CSS1Compat"==document.compatMode)return{x:document.documentElement.scrollLeft,y:document.documentElement.scrollTop}};b.getViewportSize=function(){return b.hasPointerEvent&&1<navigator.msMaxTouchPoints?{w:document.documentElement.clientWidth||c.innerWidth,
h:document.documentElement.clientHeight||c.innerHeight}:b.isMobile?{w:c.innerWidth,h:c.innerHeight}:{w:document.documentElement.clientWidth||c.innerWidth,h:document.documentElement.clientHeight||c.innerHeight}};b.getViewportMouseCoordinates=function(a){var c=b.getScrollOffsets();return a.touches?{screenX:void 0==a.touches[0]?a.touches.pageX-c.x:a.touches[0].pageX-c.x,screenY:void 0==a.touches[0]?a.touches.pageY-c.y:a.touches[0].pageY-c.y}:{screenX:void 0==a.clientX?a.pageX-c.x:a.clientX,screenY:void 0==
a.clientY?a.pageY-c.y:a.clientY}};b.supportCalc=function(){return checkCalc("-webkit-")||checkCalc("-moz-")||checkCalc()};checkCalc=function(a){a=a||"";var b=document.createElement("div");b.style.cssText=a+"width: calc(1px);";return!!b.style.length};b.supportsTransitions=function(){var a=document.createElement("p").style;return"transition"in a||"WebkitTransition"in a||"MozTransition"in a||"msTransition"in a||"OTransition"in a};b.hasCanvas=function(){return!!document.createElement("canvas")};b.hasFullscreen=
function(){return b.test.requestFullscreen||b.test.mozRequestFullScreen||b.test.msRequestFullscreen||b.test.oRequestFullscreen||b.test.webkitRequestFullScreen};b.preventSelect=function(a){jQuery(a).each(function(){jQuery(this).attr("unselectable","on").css({"-moz-user-select":"none","-webkit-user-select":"none","user-select":"none"}).each(function(){this.onselectstart=function(){return!1}})})};b.disableSelection=function(a){try{a.style.userSelect="none"}catch(f){}try{a.style.MozUserSelect="none"}catch(f){}try{a.style.webkitUserSelect=
"none"}catch(f){}try{a.style.khtmlUserSelect="none"}catch(f){}try{a.style.oUserSelect="none"}catch(f){}try{a.style.msUserSelect="none"}catch(f){}try{a.msUserSelect="none"}catch(f){}a.onselectstart=function(){return!1}};b.counter=function(a){return 9>a?"0"+(a+1):a+1};b.isNumber=function(a){return!isNaN(parseFloat(a))&&isFinite(a)};b.getRandomInt=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};b.formatCurrentTime=function(a){a=Math.round(a);minutes=Math.floor(a/60);minutes=10<=minutes?minutes:
""+minutes;a=Math.floor(a%60);return minutes+":"+(10<=a?a:"0"+a)};b.formatDuration=function(a){a=Math.round(a);minutes=Math.floor(a/60);minutes=10<=minutes?minutes:""+minutes;a=Math.floor(a%60);return minutes+":"+(10<=a?a:"0"+a)};b.hmsToSecondsOnly=function(a){a=a.split(":");for(var b=0,d=1;0<a.length;)b+=d*parseInt(a.pop()),d*=60;return b};b.checkBoolean=function(a){if("string"===typeof a)switch(a.toLowerCase()){case "true":case "yes":case "1":return!0;case "false":case "no":case "0":case null:return!1;
default:return!!a}else if("boolean"===typeof a)return!!a};c.AWPUtils=b})(window);
(function(c,b){c.AWPTooltip=function(a){b("body");b(document);var f=b(c),d=a.parent,A=!1,l;this.setData=function(){l=0<d.find(".awp-tooltip").length?d.find(".awp-tooltip"):b('<div class="awp-tooltip"><p class="awp-tooltip-inner"></p></div>').appendTo(d).hide()};this.show=function(){};this.hide=function(){l.hide()};this.seekbar=function(a,b,c,F){if(A)return!1;l.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(c)+" / "+AWPUtils.formatDuration(F));c=d.offset().left;F=d.offset().top;
b.offset();var p=b.offset().top;b.outerWidth();var r=b.outerHeight(),n=l.outerWidth(),I=l.outerHeight(),x=f.width();f.height();var y=f.scrollLeft();f.scrollTop();a=a.pageX;var J=a-c;if(b.hasClass("awp-tooltip-top")){var h=J-n/2;var V=p-F-I}else b.hasClass("awp-tooltip-bottom")&&(h=J-n/2,V=p-F+r+15);h+n+c-y>x&&(h=a-c-n);0>h+c-y&&(h=a-c);h+n+c-y>x&&(h=x-n-c+y);l.css({left:parseInt(h,10)+"px",top:parseInt(V,10)+"px"}).show()};this.circle=function(a,b,c,f){if(A)return!1;l.addClass("awp-tooltip-num").find("p").text(AWPUtils.formatCurrentTime(c)+
" / "+AWPUtils.formatDuration(f));a=d.offset().left;c=d.offset().top;f=b.offset().left;var p=b.offset().top,r=b.outerWidth();b.outerHeight();var F=l.outerWidth(),I=l.outerHeight();if(b.hasClass("awp-tooltip-top")){var x=f-a+r/2-F/2;var y=p-c-I-10}l.css({left:parseInt(x,10)+"px",top:parseInt(y,10)+"px"}).show()};this.volume=function(a,b,c){if(A)return!1;l.addClass("awp-tooltip-num").find("p").text(c+" %");c=d.offset().left;var p=d.offset().top,f=b.offset().left,r=b.offset().top,n=b.outerWidth(),G=
b.outerHeight(),x=l.outerWidth(),y=l.outerHeight(),J=a.pageX-c;a=a.pageY-p;if(b.hasClass("awp-tooltip-top"))if(b.hasClass("awp-vertical")){var h=f-c+n/2-x/2;var V=a-y-10}else h=J-x/2,V=r-p-y;else b.hasClass("awp-tooltip-bottom")?b.hasClass("awp-vertical")?(h=f-c+n/2-x/2,V=a+y+10):(h=J-x/2,V=r-p+G+10):b.hasClass("awp-tooltip-left")&&b.hasClass("awp-vertical")&&(h=f-c-x-5,V=a-y/2);l.css({left:parseInt(h,10)+"px",top:parseInt(V,10)+"px"}).show()};this.controls=function(a,b){if(A)return!1;l.removeClass("awp-tooltip-num").find("p").text(b);
var c=d.offset().left,f=d.offset().top,t=a.offset().left,r=a.offset().top,n=a.outerWidth(),G=a.outerHeight(),x=l.outerWidth(),y=l.outerHeight();a.hasClass("awp-tooltip-top")?(c=t-c+n/2-x/2,f=r-f-y):a.hasClass("awp-tooltip-top-right")?(c=t-c,f=r-f-y):a.hasClass("awp-tooltip-top-left")?(c=t-c+n-x,f=r-f-y):a.hasClass("awp-tooltip-right")?(c=t-c+n+10,f=r-f+G/2-y/2):a.hasClass("awp-tooltip-bottom")?(c=t-c+n/2-x/2,f=r-f+G+10):a.hasClass("awp-tooltip-bottom-left")?(c=t-c+n-x,f=r-f+G+10):a.hasClass("awp-tooltip-left")?
(c=t-c-10-x,f=r-f+G/2-y/2):(c=t-c+n/2-x/2,f=r-f-y);l.css({left:parseInt(c,10)+"px",top:parseInt(f,10)+"px"}).show()};this.setValue=function(a){l.find("p").text(a)};this.setState=function(a){A=a};this.setData()}})(window,jQuery);
(function(c,b){c.AWPTouchManager=function(a){function f(a){C||b(I).trigger("AWPTouchManager.MOUSE_MOVE",{elem:b(a.currentTarget),e:a})}function d(a){C||(b(a.currentTarget).off("mousemove",f).off("mouseleave",d),p.off("mouseleave",A),b(I).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:b(a.currentTarget),e:a}))}function A(a){b(a.currentTarget).off("mousemove",f).off("mouseleave",d);p.off("mouseleave",A);b(I).trigger("AWPTouchManager.MOUSE_LEAVE",{elem:b(a.currentTarget),e:a})}function l(a){y&&(J=[a.pageX,
a.pageY]);if(!C){var c;if("touchstart"==a.type)if((c=a.originalEvent.touches)&&0<c.length)c=c[0];else return!1;else c=a.originalEvent,a.preventDefault();C=!0;p.on(G,function(a){a:if(!y||a.pageX!==J[0]||a.pageY!==J[1]){if("touchmove"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else break a;if(1<c.length)break a;c=c[0]}else c=a.originalEvent;
a.preventDefault();b(I).trigger("AWPTouchManager.DRAG_MOVE",{elem:t,point:c,e:a})}}).on(x,function(a){r(a)});t.on(x,function(a){r(a)});b(I).trigger("AWPTouchManager.DRAG_START",{elem:t,point:c,e:a})}return!1}function r(a){if(C){C=!1;p.off(G).off(x);t.off(x);if("touchend"==a.type){if(a.originalEvent.touches&&a.originalEvent.touches.length)var c=a.originalEvent.touches;else if(a.originalEvent.changedTouches&&a.originalEvent.changedTouches.length)c=a.originalEvent.changedTouches;else return!1;if(1<c.length)return!1;
c=c[0]}else c=a.originalEvent;a.preventDefault();F||p.off("mouseleave",A);b(I).trigger("AWPTouchManager.DRAG_RELEASE",{name:"DRAG_RELEASE",elem:t,point:c,e:a})}return!1}var I=this;b("body");var p=b(document);b(c);var F=AWPUtils.isMobile(),t,C=!1,n,G,x,y=AWPUtils.isChrome(),J=[];this.setData=function(){"ontouchstart"in c?(n="touchstart.ap mousedown.ap",G="touchmove.ap mousemove.ap",x="touchend.ap mouseup.ap"):c.PointerEvent?(n="pointerdown.ap",G="pointermove.ap",x="pointerup.ap"):(n="mousedown.ap",
G="mousemove.ap",x="mouseup.ap");var h,r=a.length;for(h=0;h<r;h++)a[h].on(n,function(a){a.preventDefault();if(C)return!1;t=b(this);l(a);return!1});if(!F)for(h=0;h<r;h++)a[h].on("mouseenter",function(a){if(C)return!1;t=b(this).on("mouseleave",d);if(t.data("apmove"))t.on("mousemove",f);p.on("mouseleave",A);b(I).trigger("AWPTouchManager.MOUSE_ENTER",{elem:t,e:a})})};this.isDrag=function(){return C};this.setData()}})(window,jQuery);
(function(c,b){c.AWPDownloadManager=function(a){function f(a,c,f){b.ajax({type:"POST",url:r+"includes/mail.php",data:"mail="+a+"&title="+c+"&path="+f}).done(function(a){F=!1}).fail(function(a,b,c){console.log("Send email error: "+a.responseText);d();F=!1});p.css({marginTop:parseInt(-p.height()/2,10)+"px",display:"block"}).stop().animate({opacity:1},{duration:500});n&&clearTimeout(n);n=setTimeout(d,2E3)}function d(){n&&clearTimeout(n);p.stop().animate({opacity:0},{duration:500,complete:function(){p.css("display",
"none")}})}var A=AWPUtils.isMobile();b("body");b(document);var l=a.parent,r=a.settings.sourcePath,I,p,F,t,C,n;this.setData=function(){I=0<l.find("iframe.awp-dl-iframe").length?l.find("iframe.awp-dl-iframe"):b('<iframe class="awp-dl-iframe"/>').css({position:"absolute",left:"-10000px",display:"none"}).appendTo(l);A&&(p=l.find(".awp-download-confirm"))};this.download=function(a,b){if(F)return!1;if("file:"==c.location.protocol)return console.log("Downloading files locally is not possible! This requires online server connection."),
!1;var d=a;var l=b;d.indexOf("\\")&&(d=d.replace(/\\/g,"/"));d.match(/^http([s]?):\/\/.*/)||(d=AWPUtils.qualifyURL(d));A||(l=l.replace(/[^A-Z0-9\-_\.]+/ig,"_"));50<l.length&&(l=l.substr(0,50)+"...");A||/\.(mp3)$/i.test(l)||(l+=".mp3");if(A){F=!0;if(!t){for(var h=prompt("Please enter your email address where download link will be sent:");(!AWPUtils.validateEmail(h)||AWPUtils.isEmpty(h))&&null!=h;)h=prompt("Please enter a valid email address:");(C=h)&&(t=!0)}C?f(C,l,d):F=!1}else I.attr("src",r+"includes/dl.php?path="+
d+"&title="+l)};this.setData()}})(window,jQuery);
(function(c,b){c.AWPShareManager=function(a){AWPUtils.isMobile();var b=a.settings.facebookAppId,d="https:"==c.location.protocol?"https:":"http:";this.setData=function(){if(AWPUtils.isEmpty(b))console.log("facebookAppId has not been set in settings!");else if(!c.FB&&b&&!document.body.querySelector("#fb-root")){var a=document.createElement("script");a.text="window.fbAsyncInit=function(){FB.init({appId:'"+b+"',status:true,xfbml:true})};(function(e,t,n){var r,i=e.getElementsByTagName(t)[0];if(e.getElementById(n)){return}r=e.createElement(t);r.id=n;r.src='"+d+
"//connect.facebook.net/en_US/all.js';i.parentNode.insertBefore(r,i)})(document,'script','facebook-jssdk')";var l=document.createElement("div");l.id="fb-root";document.body.appendChild(l);document.body.appendChild(a)}};this.share=function(a,b,f){var l=(c.screen.width-600)/2,A=(c.screen.height-300)/2,r=b.description||"",t=b.thumb?AWPUtils.qualifyURL(b.thumb):"";b=b.share;AWPUtils.relativePath(t)||(t=AWPUtils.qualifyURL(t));if("facebook"==a){var C=d+"//www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(b);
if(c.FB){c.FB&&FB.ui({method:"feed",name:document.title,link:b,picture:t,caption:f});return}}else"twitter"==a?C=d+"//twitter.com/share?url="+encodeURIComponent(b)+"&text="+encodeURIComponent(f):"tumblr"==a&&(C=d+"//www.tumblr.com/share/link?url="+encodeURIComponent(b)+"&amp;name="+encodeURIComponent(f)+"&amp;description="+encodeURIComponent(r));C&&c.open(C,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+l+",top="+A)};this.setData()}})(window,jQuery);
(function(c,b){c.AWPSoundLoader=function(a){function f(){C.length?(t=C.shift(),G=0,J=t.limit||500,d()):b(I).trigger("AWPSoundLoader.END_LOAD",[n])}function d(){if("file:"==c.location.protocol)alert("Using "+t.type+" locally is not possible! This requires online server connection!"),f();else{var a=t.type,d=t.path;"podcast"==a?(a=F+"?url="+encodeURIComponent(d),b.ajax({url:a,dataType:"json",cache:!1}).done(function(a){var c=AWPUtils.parseXML(a.contents),d,h,l,A=0;b(c).find("image").length&&b(c).find("image").attr("href")?
l=b(c).find("image").attr("href"):b(a.contents).find("itunes\\:image").length&&b(a.contents).find("itunes\\:image").attr("href")&&(l=b(a.contents).find("itunes\\:image").attr("href"));b(c).find("item").each(function(){if(A==J)return!1;d=b(this);h=b.extend(!0,{},t);h.type="audio";h.mp3=d.find("enclosure").attr("url");p.createDownloadIconsInPlaylist&&!h.download&&(h.download=h.mp3);!h.title&&d.find("title").length&&(h.title=d.find("title").text());!h.artist&&d.find("author").length&&(h.artist=d.find("author").text());
!h.description&&d.find("description").length&&(h.description=d.find("description").text());!h.duration&&d.find("duration").length&&(h.duration=d.find("duration").text());h.thumb||(d.find("image").length&&d.find("image").attr("href")?h.thumb=d.find("image").attr("href"):l&&(h.thumb=l));d.find("link").length&&(h.share||(h.share=d.find("link").text()),!h.link&&p.createLinkIconsInPlaylist&&(h.link=d.find("link").text()));n.push(h);A++});f()}).fail(function(a,b,c){console.log(a,b,c);f()})):"soundcloud"==
a&&(x?l(d):A(d))}}function A(a){if(AWPUtils.isEmpty(y))return alert("soundCloudAppId has not been set!"),f(),!1;var b=document.createElement("script");b.src="https://connect.soundcloud.com/sdk.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d);var h=setInterval(function(){c.SC&&(h&&clearInterval(h),SC.initialize({client_id:y}),x=!0,l(a))},100)}function l(a){SC.get(a,{limit:200,linked_partitioning:1},function(a,b){if(b)console.log("Error getSoundCloudPage: "+b),f();
else{if("track"==a.kind)r(a);else if("playlist"==a.kind){var c,d=a.tracks.length;if(n.length+d>=J){d=J-n.length;var h=!0}for(c=0;c<d;c++)r(a.tracks[c],!0)}else if(a.collection)for(d=a.collection.length,n.length+d>=J&&(d=J-n.length,h=!0),c=0;c<d;c++)r(a.collection[c],!0);a.next_href&&!h?l(a.next_href):f()}})}function r(a,b){if(a.streamable&&a.stream_url){var c=jQuery.extend(!0,{},t);c.deeplink&&"undefined"!==typeof b&&(c.deeplink+=(G+1).toString(),G++);c.type="audio";a.duration&&(c.duration=a.duration);
c.mp3=a.stream_url+"?client_id="+y;p.createDownloadIconsInPlaylist&&"undefined"===typeof c.download&&a.downloadable&&a.download_url&&(c.download=c.mp3.replace(/\/stream\\?/,"/download"));!c.title&&a.title&&(c.title=a.title);!c.description&&a.description&&(c.description=a.description);!c.thumb&&a.artwork_url&&(c.thumb=a.artwork_url,c.thumbQuality&&(c.thumb=c.thumb.replace("large.jpg",c.thumbQuality)));c.favoritings_count=parseInt(a.favoritings_count?a.favoritings_count:0,10);c.playback_count=parseInt(a.playback_count?
a.playback_count:0,10);c.hotness=c.favoritings_count+c.playback_count;a.permalink_url&&(c.share||(c.share=a.permalink_url),p.createLinkIconsInPlaylist&&!c.link&&(c.link=a.permalink_url));n.push(c)}}var I=this,p=a.settings,F=p.sourcePath+"includes/ba-simple-proxy.php",t,C=[],n=[],G,x,y=p.soundCloudAppId;b("<div/>");var J;this.setData=function(a){n=[];C=b.extend(!0,[],[a]);f()}}})(window,jQuery);
(function(c,b){c.AWPPlaylistManager=function(a){function c(){3>d.playlistItems?d.randomPlay=!1:d.randomArr=AWPUtils.randomiseArray(d.playlistItems)}var d=this;this.loopingOn=a.loopingOn;this.randomPlay=a.randomPlay;this.playlistItems;this.lastInOrder=!1;this.counter=-1;this.lastPlayedFromPlaylistClick;this.lastRandomCounter;this.randomPaused=!1;this.randomArr=[];this.playlistSelect=!1;this.setCounter=function(a,f){"undefined"===typeof f&&(f=!0);d.counter=f?d.counter+parseInt(a,10):parseInt(a,10);
if(isNaN(d.counter))alert("AWPPlaylistManager message: No active media, counter = "+d.counter);else if(d.lastInOrder=!1,d.loopingOn){if(d.randomPlay)if(d.counter>d.playlistItems-1){d.counter=d.randomArr[d.playlistItems-1];c();if(d.randomArr[0]==d.counter){var l=d.randomArr.splice(0,1);d.randomArr.push(l)}d.counter=0;b(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")}else 0>d.counter&&(d.counter=d.randomArr[0],c(),d.randomArr[d.playlistItems-1]==d.counter&&(l=d.randomArr.splice(d.playlistItems-
1,1),d.randomArr.unshift(l)),d.counter=d.playlistItems-1);else d.counter>d.playlistItems-1?(d.counter=0,b(d).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")):0>d.counter&&(d.counter=d.playlistItems-1);b(d).trigger("AWPPlaylistManager.COUNTER_READY")}else d.counter>d.playlistItems-1?(d.counter=d.playlistItems-1,d.lastInOrder=!0):0>d.counter&&(d.counter=0),d.lastInOrder?b(d).trigger("AWPPlaylistManager.PLAYLIST_END"):b(d).trigger("AWPPlaylistManager.COUNTER_READY")};this.getCounter=function(){return d.randomPlay?
d.playlistSelect?d.counter:d.randomArr[d.counter]:d.counter};this.advanceHandler=function(a){d.playlistSelect=!1;d.randomPaused?(d.randomPaused=!1,d.lastRandomCounter+a>d.playlistItems-1?(d.counter=d.playlistItems-1,b(d).trigger("AWPPlaylistManager.COUNTER_READY")):0>d.lastRandomCounter+a?(d.counter=0,b(d).trigger("AWPPlaylistManager.COUNTER_READY")):d.setCounter(d.lastRandomCounter+a,!1)):d.setCounter(a)};this.processPlaylistRequest=function(a){d.playlistSelect=!1;d.randomPlay&&(d.playlistSelect=
!0,d.lastPlayedFromPlaylistClick=a,d.randomPaused||(d.lastRandomCounter=d.counter,d.randomPaused=!0));this.setCounter(a,!1)};this.setPlaylistItems=function(a,b){"undefined"===typeof b&&(b=!0);b&&(d.counter=-1);d.playlistItems=a;d.randomPlay&&c()};this.reSetCounter=function(a){"undefined"===typeof a?d.counter=-1:(a=parseInt(a,10),d.playlistItems?(a>d.playlistItems-1?a=d.playlistItems-1:0>a&&(a=0),d.counter=a):d.counter=-1)};this.setRandom=function(a){d.randomPlay=a;d.randomPlay&&c();if(d.randomPlay){var b=
d.randomArr.length;for(a=0;a<b;a++)if(d.randomArr[a]==d.counter){if(0==a)break;a=d.randomArr.splice(a,1);d.randomArr.unshift(parseInt(a,10));break}d.counter=0}else d.randomPaused?(d.counter=d.lastPlayedFromPlaylistClick,d.randomPaused=!1):d.counter=d.randomArr[d.counter]};this.setLooping=function(a){d.loopingOn=a}}})(window,jQuery);
(function(c){c.fn.awp=function(b){function a(e){if(!k)return!1;0<z?(Ra=z,z=0):z=Ra;f();"undefined"!==typeof e&&"undefined"!==typeof Q&&void 0!=ta.attr("data-awptooltip")&&Q.controls(ta,0==z?"UnMute":"Mute")}function f(e){"undefined"!==typeof e&&(z=e);"undefined"!==typeof z&&(u.volume=z,"undefined"!==typeof g&&g.setVolume(z));ua&&(aa?lb.css("width",z*W+"px"):lb.css("height",z*W+"px"));0==z?ua&&ta.find("i").removeClass("fa-volume-up fa-volume-down").addClass("fa-volume-off"):ua&&ta.find("i").removeClass("fa-volume-off fa-volume-down").addClass("fa-volume-up");
awpVolumeChange(w,D,z)}function d(e){e.preventDefault();if(!k)return!1;var a=c(e.currentTarget),b=a.attr("data-id");if(b==m.getCounter())return!1;Sa=!0;m.processPlaylistRequest(b);awpPlaylistItemClick(w,D,a,b,e)}function A(e){e.preventDefault();if(!k)return!1;e=c(e.currentTarget);var a=e.attr("data-id");if(a==m.getCounter())return!1;e.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected");awpPlaylistItemRollover(w,D,e,a)}function l(e){e.preventDefault();if(!k)return!1;e=c(e.currentTarget);
var a=e.attr("data-id");if(a==m.getCounter())return!1;e.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected");awpPlaylistItemRollout(w,D,e,a)}function r(e){if(!k)return!1;e=c(e.currentTarget);e.hasClass("awp-prev-toggle")?w.previousMedia():e.hasClass("awp-playback-toggle")?w.togglePlayback():e.hasClass("awp-next-toggle")?w.nextMedia():e.hasClass("awp-loop-toggle")?(S=!S,m.setLooping(S),S?ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):ka.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):
e.hasClass("awp-player-volume")?e.hasClass("awp-toggle-mute")&&a():e.hasClass("awp-random-toggle")?(T=!T,m.setRandom(T),T?la.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):la.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")):e.hasClass("awp-sort-alpha")?(w.sort("title",Ba),(Ba=!Ba)?e.find("i").removeClass("fa-sort-alpha-desc").addClass("fa-sort-alpha-asc"):e.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc")):e.hasClass("awp-share-item")&&
void 0!=e.attr("data-type")&&"undefined"!==typeof mb&&q.share&&!AWPUtils.isEmpty(q.share)&&mb.share(e.attr("data-type").toLowerCase(),q,va(m.getCounter()))}function I(e){if(!k)return!1;e.preventDefault();if("undefined"!==typeof Ta&&Ta.isDrag())return!1;e=c(e.currentTarget);var a=e.find("i");a.hasClass("awp-icon-color")&&a.removeClass("awp-icon-color").addClass("awp-icon-rollover-color");"undefined"!==typeof Q&&void 0!=e.attr("data-awptooltip")&&(a=e.hasClass("awp-player-volume")?0==z?"UnMute":"Mute":
e.attr("data-awptooltip"),Q.controls(e,a))}function p(a){if(!k)return!1;a.preventDefault();a=c(a.currentTarget);var e=a.find("i");a.hasClass("awp-random-toggle")&&T||a.hasClass("awp-loop-toggle")&&S||e.hasClass("awp-icon-rollover-color")&&e.removeClass("awp-icon-rollover-color").addClass("awp-icon-color");"undefined"!==typeof Q&&Q.hide()}function F(){if(-1!=m.getCounter()){var a=Z,c=E.children("div.awp-playlist-item[data-id="+a+"]"),b=c.find(".awp-playlist-non-selected, .awp-playlist-selected");c.length&&
(a=c.attr("data-id"),b.removeClass("awp-playlist-selected").addClass("awp-playlist-non-selected"),"undefined"!==typeof awpPlaylistItemEnabled&&awpPlaylistItemEnabled(w,D,c,a))}}function t(){-1!=Z&&F();var a=m.getCounter(),c=E.children("div.awp-playlist-item[data-id="+a+"]"),b=c.find(".awp-playlist-non-selected, .awp-playlist-selected");c.length&&(Z=a,b.removeClass("awp-playlist-non-selected").addClass("awp-playlist-selected"),Ca&&0<B&&(Sa||("h"==Da.charAt(0)?fa.mCustomScrollbar("scrollTo",parseInt(c.position().left),
{scrollInertia:500}):fa.mCustomScrollbar("scrollTo",parseInt(c.position().top),{scrollInertia:500})),Sa=!1),"undefined"!==typeof awpPlaylistItemDisabled&&awpPlaylistItemDisabled(w,D,c,a))}function C(a){Ea=c.ajax({url:ma+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_read_peaks"},{name:"id",value:a},{name:"path",value:q.peakdir||null}],dataType:"json"}).done(function(a){a.length?(g.backend.peaks=a,Fa=!0,Ua?g.drawBuffer():g.load(N,g.backend.peaks)):(g.backend.supportsWebAudio()?(Va=!0,
q.remote&&(wa.css("opacity",1).html("Loading waveform..."),g.setSkipArrayBuffer(!0),x())):q.peakImage&&(ha=!0,Wa.empty().append('<img src="'+q.peakImage.load+'" alt="load"/>'),na.empty().append('<img src="'+q.peakImage.progress+'" alt="progress"/>'),U.css("display","block"),na.width(U.width()),U.removeClass("awp-hidden").addClass("awp-visible"),Ga()),g.load(N))}).fail(function(a,e,c){console.log(a,e,c)})}function n(a,b){c.ajax({url:ma+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_write_peaks"},
{name:"peaks",value:a},{name:"id",value:b},{name:"path",value:q.peakdir||null}],dataType:"json"}).done(function(a){}).fail(function(a,e,c){console.log(a.responseText)})}function G(){if(Kb&&q.wav)N=q.wav;else if(Lb&&q.aac)N=q.aac;else if(Mb&&q.mp3)N=q.mp3;else{alert("No required audio format supplied! Please add mp3 audio format to play!");return}-1!=N.indexOf("ebsfm:")&&(N=atob(N.substr(6)));q.peakData?(g.backend.peaks=q.peakData,Fa=!0,g.drawBuffer(),Ua?g.drawBuffer():g.load(N,g.backend.peaks)):q.peakImage?
(ha=!0,Wa.empty().append('<img src="'+q.peakImage.load+'" alt="load"/>'),na.empty().append('<img src="'+q.peakImage.progress+'" alt="progress"/>'),U.css("display","block"),na.width(U.width()),U.removeClass("awp-hidden").addClass("awp-visible"),Ga(),g.setSkipArrayBuffer(!0),g.load(N)):C(q.peakName||q.title)}function x(){Ha=c.ajax({url:ma+"peaks/remote_dl.php",type:"post",data:[{name:"id",value:N},{name:"title",value:q.title},{name:"path",value:q.peakdir||null}],dataType:"json"}).done(function(a){console.log(a);
g._getArrayBuffer(a)}).fail(function(a,c,b){console.log(a,c,b)})}function y(a){X=!0;nb();O&&Xa();var e=Nb.find("#"+a);if(0==e.length)return alert('Failed to select playlist! Check activePlaylist option in settings. Make sure that element: "'+a+'" exist in awp-playlist-list!'),Ya.css("display","none"),X=!1;"undefined"!==typeof awpPlaylistStartLoad&&awpPlaylistStartLoad(w,D);var b,d;e.find(".awp-playlist-item").each(function(){d=c(this);b=J(d);ba.push(b)});B=ba.length;h()}function J(a){var e={};e.origclasses=
a.attr("class");e.type=e.origtype=a.attr("data-type");a.is(":empty")||(e.content=a.html());void 0!=a.attr("data-mp3")&&(e.mp3=a.attr("data-mp3"));void 0!=a.attr("data-wav")&&(e.wav=a.attr("data-wav"));void 0!=a.attr("data-aac")&&(e.aac=a.attr("data-aac"));void 0==a.attr("data-path")||AWPUtils.isEmpty(a.attr("data-path"))||(e.path=a.attr("data-path"),-1!=e.path.indexOf("ebsfm:")&&(e.path=atob(e.path.substr(6))));void 0==a.attr("data-peak-load")||AWPUtils.isEmpty(a.attr("data-peak-load"))||void 0==
a.attr("data-peak-progress")||AWPUtils.isEmpty(a.attr("data-peak-progress"))||(e.peakImage={load:a.attr("data-peak-load"),progress:a.attr("data-peak-progress")});void 0!=a.attr("data-peak-array")&&(e.peakData=a.attr("data-peak-array").split(","));void 0!=a.attr("data-peak-name")&&(e.peakName=a.attr("data-peak-name"));AWPUtils.isEmpty(a.html())||(e.content=a.html());void 0!=a.attr("data-limit")&&!AWPUtils.isEmpty(a.attr("data-limit"))&&AWPUtils.isNumber(a.attr("data-limit"))&&0!=Math.abs(parseInt(a.attr("data-limit"),
10))&&(e.limit=Math.abs(parseInt(a.attr("data-limit"),10)));void 0==a.attr("data-thumb")||AWPUtils.isEmpty(a.attr("data-thumb"))?void 0==a.attr("data-thumb-default")||AWPUtils.isEmpty(a.attr("data-thumb-default"))||(e.thumbDefault=a.attr("data-thumb-default")):e.thumb=a.attr("data-thumb");void 0==a.attr("data-thumb-quality")||AWPUtils.isEmpty(a.attr("data-thumb-quality"))||(e.thumbQuality=a.attr("data-thumb-quality"));void 0==a.attr("data-title")||AWPUtils.isEmpty(a.attr("data-title"))||(e.title=
a.attr("data-title"));void 0==a.attr("data-artist")||AWPUtils.isEmpty(a.attr("data-artist"))||(e.artist=a.attr("data-artist"));void 0==a.attr("data-description")||AWPUtils.isEmpty(a.attr("data-description"))||(e.description=a.attr("data-description"));void 0!=a.attr("data-download")&&(e.download=a.attr("data-download"));void 0!=a.attr("data-id3")&&(e.id3=!0);void 0==a.attr("data-dir-url")||AWPUtils.isEmpty(a.attr("data-dir-url"))||(e.dirurl=a.attr("data-dir-url"));void 0==a.attr("data-peak-dir")||
AWPUtils.isEmpty(a.attr("data-peak-dir"))||(e.peakdir=a.attr("data-peak-dir"));void 0!=a.attr("data-start")&&!AWPUtils.isEmpty(a.attr("data-start"))&&AWPUtils.isNumber(a.attr("data-start"))&&0!=a.attr("data-start")&&(e.start=Math.abs(a.attr("data-start")));void 0!=a.attr("data-end")&&!AWPUtils.isEmpty(a.attr("data-end"))&&AWPUtils.isNumber(a.attr("data-end"))&&0!=a.attr("data-end")&&(e.end=Math.abs(a.attr("data-end")));void 0!=a.attr("data-duration")&&!AWPUtils.isEmpty(a.attr("data-duration"))&&AWPUtils.isNumber(a.attr("data-duration"))&&
0!=Math.abs(a.attr("data-duration"))&&(e.duration=Math.abs(a.attr("data-duration")));void 0!=a.attr("data-playback-rate")&&(e.playbackRate=1,!AWPUtils.isEmpty(a.attr("data-playback-rate"))&&AWPUtils.isNumber(a.attr("data-playback-rate"))&&0!=a.attr("data-playback-rate")&&(e.playbackRate=Math.abs(a.attr("data-playback-rate"))));void 0==a.attr("data-link")||AWPUtils.isEmpty(a.attr("data-link"))||(e.link=a.attr("data-link"),e.target="_blank",void 0==a.attr("data-target")||AWPUtils.isEmpty(a.attr("data-target"))||
(e.target=a.attr("data-target")));void 0!=a.attr("data-share")&&(e.share=a.attr("data-share"));void 0!=a.attr("data-remote")&&(e.remote=!0);void 0==a.attr("data-sort")||AWPUtils.isEmpty(a.attr("data-sort"))||(e.sort=a.attr("data-sort"));return e}function h(){oa++;if(oa>B-1)Ib();else{var a=ba[oa],b=ba[oa].type;/^audio$/.test(b)?(Y.push(a),h()):-1<c.inArray(b,Ob)?ob.setData(a):/^folder$/.test(b)?V(a):/^gdrive-folder$/.test(b)?Hb(a):(console.log("Wrong data-type in playlist! Type = "+b),h())}}function V(a){if("file:"==
window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),h(),!1;var e=a.path.replace(/\/\//g,"/"),b=ma+"includes/folder_parser.php";e={dir:e,limit:a.limit||1E4};a.id3&&(Za=ia=Y.length-1);c.ajax({type:"GET",url:b,data:e,dataType:"json"}).done(function(e){a.sort&&("filename-asc"==a.sort?AWPUtils.keysrt(e,"filename"):"filename-desc"==a.sort?AWPUtils.keysrt(e,"filename",!0):"date-asc"==a.sort?AWPUtils.keysrt(e,"filemtime"):
"date-desc"==a.sort&&AWPUtils.keysrt(e,"filemtime",!0));var b,d=e.length;for(b=0;b<d;b++){var R=e[b];var M=c.extend(!0,{},a);M.type="audio";var g=M.dirurl?M.dirurl+R.basename:R.fullpath;M[R.extension]=g;M.title||(M.title=R.filename);pb&&!M.download&&(M.download=g);M.share||(M.share=g);qb&&!M.link&&(M.link=g);Y.push(M);ia++}a.id3?Pa():h()}).fail(function(a,e,c){console.log("Error processing folder: "+a.responseText);h()})}function Hb(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),
h(),!1;if(AWPUtils.isEmpty(u.gDriveAppId))return console.log("gDriveAppId has not been set in settings!"),h(),!1;c.ajax({url:"https://www.googleapis.com/drive/v3/files?q='"+a.path+"'+in+parents&pageSize=1000&key="+u.gDriveAppId,dataType:"jsonp"}).done(function(e){var b,d=e.files.length,R=[],g=[];for(b=0;b<d;b++){var f=e.files[b];/mp3|mpeg|mpeg3|wav|aac|adts/.test(f.mimeType)?(g.push(f),AWPUtils.keysrt(g,"name")):/jpg|jpeg|png/.test(f.mimeType)&&(R.push(f),AWPUtils.keysrt(R,"name"))}a.sort&&("filename-asc"==
a.sort?(AWPUtils.keysrt(g,"name"),AWPUtils.keysrt(R,"name")):"filename-desc"==a.sort&&(AWPUtils.keysrt(g,"name",!0),AWPUtils.keysrt(R,"name",!0)));d=g.length;for(b=0;b<d;b++){f=g[b];e=c.extend(!0,{},a);e.type="audio";var l=f.name.substr(f.name.lastIndexOf(".")+1);e[l.toLowerCase()]="https://drive.google.com/uc?export=download&id="+f.id;R.length&&!e.thumb&&R[b]&&(e.thumb="https://drive.google.com/uc?export=view&id="+R[b].id);e.title||(e.title=f.name.substr(0,f.name.lastIndexOf(".")));pb&&!e.download&&
(e.download="https://drive.google.com/uc?export=download&id="+f.id);e.share||(e.share="https://drive.google.com/open?id="+f.id);qb&&!e.link&&(e.link="https://drive.google.com/open?id="+f.id);Y.push(e)}h()}).fail(function(a,e,b){console.log("Error processing gdrive folder: "+a.responseText);h()})}function Pa(){var a=Y[ia];jsmediatags.read(a.mp3||a.wav||a.aac,{onSuccess:function(e){var b=e.tags;e=b.picture;b.artist&&(a.artist=b.artist);b.title&&(a.title=b.title);b.album&&(a.album=b.album);if(e){b="";
var c,d=e.data.length;for(c=0;c<d;c++)b+=String.fromCharCode(e.data[c]);a.thumb="data:"+e.format+";base64,"+window.btoa(b)}ia--;ia>Za?Pa():h()},onError:function(a){console.log("ID3 error: ",a.type,a.info);ia--;ia>Za?Pa():h()}})}function Ib(){var a,b=ca?L:H.length,g=Y.length,f=0;for(a=0;a<g;a++){var h=a+b;ca&&f++;var k=Y[a];var q=k.type;if(ja){k.origclasses||(k.origclasses="awp-playlist-item");var n=c('<div class="'+k.origclasses+'"/>').attr({"data-type":q});delete k.origclasses;if(ca){u?u.after(n):
pa?n.appendTo(E):E.children("div").eq(L).before(n);var u=n}else n.appendTo(E);var r=c('<a class="awp-playlist-non-selected" href="#"/>').on("click",d).appendTo(n);if(!qa)r.on("mouseenter",A).on("mouseleave",l);if(-1!=c.inArray("thumb",rb)){var p=k.thumb||k.thumbDefault;if(p){var t=new Image;t.className="awp-hidden";t.onload=function(){this.className="awp-visible"};t.src=p;c('<span class="awp-playlist-thumb"></span>').append(t).appendTo(r)}}-1!=c.inArray("title",rb)&&c('<span class="awp-playlist-title"></span>').appendTo(r);
k.link&&(p=c('<a class="awp-link" href="'+k.link+'" target="'+(k.target||"_blank")+'"><i class="fa fa-external-link"></i></a>'),r.after(p));k.download&&(p=sb?c('<a class="awp-download" href="'+k.download+'" download title="Download"><i class="fa fa-download"></i></a>'):c('<a class="awp-download" href="#" title="Download"><i class="fa fa-download"></i></a>'),r.after(p));k.content&&(n.after(k.content),delete k.content)}H.splice(h,0,{id:h,type:q,data:k})}ja&&Jb();O=E;Qa();console.log("playlistDataArr = ",
H);ca||$a?(h=m.getCounter(),m.setPlaylistItems(B,!1),L<=h&&(pa||m.reSetCounter(h+f)),xa?(xa=!1,ya&&!qa&&(da=!0),m.setCounter(L,!1)):ya&&m.setCounter(L,!1),-1!=m.getCounter()&&(Z=m.getCounter())):m.setPlaylistItems(B);tb();0==B&&"undefined"!==typeof awpPlaylistEmpty&&awpPlaylistEmpty(w,D,E);Ia=!0;"undefined"!==typeof awpPlaylistEndLoad&&awpPlaylistEndLoad(w,D,E)}function Qa(){B=H.length;if(ja){var a=0,b,d,g,f;Ja=[];E.find("div.awp-playlist-item").each(function(){d=c(this).attr("data-id",a);g=d.find(".awp-playlist-non-selected, .awp-playlist-selected").attr("data-id",
a);f=g.find(".awp-playlist-title");f.length&&(b=va(a),ab&&(Ja.push(b.toLowerCase()),H[a].data.title_full=b),ub?f.html(AWPUtils.counter(a)+vb+b):f.html(b));H[a].id=a;a++});Ca&&Ka&&0<B&&"h"==Da.charAt(0)&&fa.mCustomScrollbar("update")}}function Jb(){E.children(".awp-playlist-item").each(function(){if(!sb)c(this).find("a[class=awp-download]").off("click").on("click",function(a){a.preventDefault();"undefined"!==typeof wb&&(a=c(this).parent().attr("data-id"),a=H[a].data,"undefined"===typeof a.download||
AWPUtils.isEmpty(a.download)||wb.download(a.download,a.title||"media"))})})}function kb(a){var e="h"==Da.charAt(0)?"x":"y";fa.mCustomScrollbar({axis:e,theme:a||u.playlistScrollTheme,scrollInertia:0,mouseWheel:{normalizeDelta:!0,deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0}});Ka=!0}function tb(){ca=$a=!1;Ya.css("display","none");X=!1;k||(k=!0,ja&&!Ka&&Ca&&kb(),f(z),awpSetupDone(w,D));if(!bb&&!ca&&0<B){var a=u.activeItem;a>B-1&&(a=B-1);-1<a&&m.setCounter(a,
!1);bb=!0}}function xb(){"undefined"!==typeof awpMediaEnd&&awpMediaEnd(w,D,m.getCounter());if(Pb)w.nextMedia();else{var a=q.start||0;"loop"==cb?g.play(a):"rewind"==cb?(g.pause(),g.seekTo(a/g.getDuration())):"stop"==cb&&g.pause()}}function yb(){k&&"undefined"!==typeof K&&(ja&&-1!=Z&&F(),La(),m.reSetCounter())}function La(){Ha&&(Ha.abort(),Ha=null);Ea&&(Ea.abort(),Ea=null);"undefined"!==typeof g&&(g.empty(),g.setSkipArrayBuffer(!1));wa.css("opacity",0);Ma.removeClass("awp-visible").addClass("awp-hidden");
ha=!1;Wa.empty();na.empty();U.css("display","none").removeClass("awp-visible").addClass("awp-hidden");za.removeClass("awp-visible").addClass("awp-hidden");Aa.removeClass("awp-visible").addClass("awp-hidden");zb&&(za.html("0:00"),Aa.html("0:00"));Qb.empty();Ab();K=null;ya=Na=P=!1;awpCleanMedia(w,D)}function Xa(){K&&La();ja&&O.find(".awp-playlist-item").remove();ra=O=null;Ia=xa=ca=!1;Z=-1;bb=!1;B=0;oa=-1;H=[];Y=[];ba=[];m.reSetCounter();ab&&Bb.val(db);Rb&&(Ba=!1,eb.find("i").removeClass("fa-sort-alpha-asc").addClass("fa-sort-alpha-desc"));
awpDestroyPlaylist(w,D,E)}function Ga(){za.removeClass("awp-hidden").addClass("awp-visible");Aa.removeClass("awp-hidden").addClass("awp-visible")}function Ab(){fb.find("i").removeClass("fa-pause").addClass("fa-play")}function nb(){Ya.css("display","block")}function gb(a){if("string"===typeof a)var b=a;else"number"===typeof a&&(b=va(a),ub&&(b=AWPUtils.counter(a)+vb+b));Sb.html(b)}function va(a){a=H[a].data;var b="";"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||
AWPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(b=a.artist):b=a.title:b=a.artist+Cb+a.title;return b}var u=c.extend({},{instanceName:"",sourcePath:"",playlistList:"",activePlaylist:"",activeItem:0,volume:.5,autoPlay:!1,randomPlay:!1,loopingOn:!0,autoAdvanceToNextMedia:!0,mediaEndAction:"loop",soundCloudAppId:"",usePlaylistScroll:!1,playlistScrollOrientation:"vertical",
playlistScrollTheme:"light",useKeyboardNavigationForPlayback:!1,facebookAppId:"",useNumbersInPlaylist:!1,numberTitleSeparator:".  ",artistTitleSeparator:" - ",playlistItemContent:"title",createDownloadIconsInPlaylist:!1,createLinkIconsInPlaylist:!1,togglePlaybackOnMultipleInstances:!1},b),v=c(this).show(),Nb=c(u.playlistList).hide(),Tb=v.find(".awp-playlist-holder"),fa=v.find(".awp-playlist-inner"),E=v.find(".awp-playlist-content"),hb=v.find(".awp-playlist-filter-msg"),eb=v.find(".awp-sort-alpha"),
Ya=v.find(".awp-preloader");v.find(".awp-player-holder");var Qb=v.find(".awp-player-thumb"),za=v.find(".awp-media-time-current"),Aa=v.find(".awp-media-time-total"),Sb=v.find(".awp-media-title");v.find(".awp-player-controls");var fb=v.find(".awp-playback-toggle"),ka=v.find(".awp-loop-toggle"),ta=v.find(".awp-player-volume"),la=v.find(".awp-random-toggle");v.find(".awp-volume-wrapper");var sa=v.find(".awp-volume-seekbar"),ea=v.find(".awp-volume-bg"),lb=v.find(".awp-volume-level"),Ma=v.find(".awp-waveform"),
wa=v.find(".awp-waveform-preloader"),U=v.find(".awp-waveform-img"),Wa=v.find(".awp-waveform-img-load"),Db=v.find(".awp-waveform-img-progress-wrap"),na=v.find(".awp-waveform-img-progress"),qa=AWPUtils.isMobile(),Mb=AWPUtils.canPlayMp3(),Kb=AWPUtils.canPlayWav(),Lb=AWPUtils.canPlayAac(),ma=u.sourcePath,D=AWPUtils.filterAllowedChars(u.instanceName),ra=u.activePlaylist,da=u.autoPlay,Ua=u.drawWaveWithoutLoad,S=u.loopingOn,T=u.randomPlay,ub=u.useNumbersInPlaylist,vb=u.numberTitleSeparator,Cb=u.artistTitleSeparator,
z=u.volume,Ca=u.usePlaylistScroll,Da=u.playlistScrollOrientation.toLowerCase(),Ub=u.useKeyboardNavigationForPlayback,Pb=u.autoAdvanceToNextMedia,cb=u.mediaEndAction,rb=u.playlistItemContent.split(","),pb=u.createDownloadIconsInPlaylist,qb=u.createLinkIconsInPlaylist,ja=Tb.length,ab=v.find(".awp-search-filter").length,Rb=eb.length,zb=za.length||Aa.length,ua=sa.length,k=!1,X=!1,w=this;c("body");var Vb=c(window),Wb=c(document),Eb=AWPUtils.isIE(),Xb=AWPUtils.isChrome(),Yb=AWPUtils.isSafari(),ib,sb=AWPUtils.hasDownloadSupport(),
Va,ha,Fa,Ha,Ea,pa,L,ca,ya,xa,$a,oa=-1,H=[],Y=[],ba=[],B=0,bb,Ia=!1,O=null,Z=-1,Na=!1,K,N,P=!1,q,Sa,Ka,Ba=!1,Ja=[],ia,Za,Ob=["podcast","soundcloud","soundcloud_query"];if(da&&!AWPUtils.iFrame&&(Xb||Yb)&&!qa){var Zb=AWPUtils.qualifyURL(ma+"data/silence.mp3");AWPUtils.iFrame=c('<iframe src="'+Zb+'" allow="autoplay" style="display:none"></iframe>').appendTo("body");var Fb=!0}"undefined"===typeof window.awp_mediaArr&&(window.awp_mediaArr=[]);awp_mediaArr.push({inst:w,id:D});qa&&(da=!1);if(Eb&&12>Eb)U.on("click",
function(a){if(ha){var b=c(a.currentTarget);a=Math.min(Math.max((a.pageX-b.offset().left)/b.width(),0),1);g.seekTo(a)}});S&&ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");T&&la.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color");if(ab)var Bb=v.find(".awp-search-filter").on("focus",function(a){c(this).val()==db&&c(this).val("")}).on("blur",function(){AWPUtils.isEmpty(c(this).val())&&c(this).val(db)}).on("keyup.apfilter",function(){if(0==Ja.length)return!1;
var a=H.length,b=c(this).val();b=Ja.filter(/./.test.bind(new RegExp(b,"i")));var d,f=0;for(d=0;d<a;d++){var g=va(d).toLowerCase();-1<c.inArray(g,b)?E.children("div.awp-playlist-item").eq(d).show():(E.children("div.awp-playlist-item").eq(d).hide(),f++)}0<a&&hb.length&&(f==a?hb.show():hb.hide());Ca&&0<B&&"h"==Da.charAt(0)&&fa.mCustomScrollbar("update");"undefined"!==typeof awpFilterChange&&awpFilterChange(w,D,E)}),db=Bb.val();var Q=new AWPTooltip({settings:u,parent:v}),wb=new AWPDownloadManager({settings:u,
parent:v}),mb=new AWPShareManager({settings:u}),m=new AWPPlaylistManager({randomPlay:T,loopingOn:S});c(m).on("AWPPlaylistManager.COUNTER_READY",function(){K&&La();ja&&t();var a=m.getCounter();q=H[a].data;K=q.type;gb(a);Fb?(Fb=!1,setTimeout(function(){G()},150)):G();"undefined"!==typeof awpItemTriggered&&awpItemTriggered(w,D,a)}).on("AWPPlaylistManager.PLAYLIST_END AWPPlaylistManager.PLAYLIST_END_ALERT",function(){"undefined"!==typeof awpPlaylistEnd&&awpPlaylistEnd(w,D)});var ob=new AWPSoundLoader({settings:u,
sourcePath:ma});c(ob).on("AWPSoundLoader.END_LOAD",function(a,b){var c,e=b.length;for(c=0;c<e;c++){var d=b[c];Y.push(d)}h()});var jb=[];ua&&(sa.data("apmove",!0),jb.push(sa));if(jb.length){var Ta=new AWPTouchManager(jb);c(Ta).on("AWPTouchManager.DRAG_START",function(a,b){}).on("AWPTouchManager.DRAG_MOVE AWPTouchManager.DRAG_RELEASE",function(a,b){if(!k)return!1;var c=b.elem,e=b.point.pageX,d=b.point.pageY;if(c.hasClass("awp-volume-seekbar")){var g=aa?e:d;aa?z=Math.max(0,Math.min(1,(g-ea.offset().left)/
W)):(z=Math.max(0,Math.min(1,(g-ea.offset().top)/W)),z=1-z);f();"undefined"!==typeof Q&&c.is('[class*="awp-tooltip"]')&&(c=aa?e-ea.offset().left:d-ea.offset().top,0>c?c=0:c>W&&(c=W),c=Math.max(0,Math.min(1,c/W)),aa||(c=1-c),c=parseInt(100*c,10),Q.volume(b.point,sa,c))}}).on("AWPTouchManager.MOUSE_MOVE",function(a,b){if(!k)return!1;var c=b.elem;a=b.e;var e=a.pageX,d=a.pageY;c.hasClass("awp-volume-seekbar")&&"undefined"!==typeof Q&&c.is('[class*="awp-tooltip"]')&&(c=aa?e-ea.offset().left:d-ea.offset().top,
0>c?c=0:c>W&&(c=W),c=Math.max(0,Math.min(1,c/W)),aa||(c=1-c),c=parseInt(100*c,10),Q.volume(a,sa,c))}).on("AWPTouchManager.MOUSE_LEAVE",function(a,b){if(!k)return!1;"undefined"!==typeof Q&&Q.hide()})}if(ua){var aa=sa.hasClass("awp-vertical")?!1:!0,Ra=.5,W=void 0!=u.volumeSize?u.volumeSize:aa?ea.width():ea.height();0>z?z=0:1<z&&(z=1);0!=z&&(Ra=z)}if(Ub)Wb.on("keyup.apnav",function(b){if(!k)return!1;var e=b.keyCode;c(b.target);37==e?w.previousMedia():39==e?w.nextMedia():32==e?w.togglePlayback():77==
e&&a()});var Gb=[v.find(".awp-next-toggle"),v.find(".awp-prev-toggle"),v.find(".awp-playlist-toggle"),v.find(".awp-share-item"),eb,ta,fb,ka,la],$b=Gb.length,Oa;for(Oa=0;Oa<$b;Oa++){var ac=c(Gb[Oa]).css("cursor","pointer").on("click",r);if(!qa)ac.on("mouseenter",I).on("mouseleave",p)}var g=Object.create(WaveSurfer);g.init({container:Ma[0],backend:"MediaElement",interact:1,hideScrollbar:!0,waveColor:u.wavesurfer.waveColor,progressColor:u.wavesurfer.progressColor,barWidth:u.wavesurfer.barWidth,cursorColor:u.wavesurfer.cursorColor,
cursorWidth:u.wavesurfer.cursorWidth,height:u.wavesurfer.height});g.on("loading",function(a){a="Loading... "+a.toString()+"%";wa.css("opacity",1).html(a)});g.on("finish",function(a){xb()});g.on("error",function(a){console.log(a)});g.on("audioprocess",function(a){a=g.getCurrentTime();var b=g.getDuration();zb&&(za.html(AWPUtils.formatCurrentTime(a)),Aa.html(AWPUtils.formatDuration(b)));ha&&Db.width(U.width()*g.backend.getPlayedPercents());q.end&&a>=q.end&&xb()});g.on("play",function(){Na||(awpMediaStart(w,
D,m.getCounter()),Na=!0);fb.find("i").removeClass("fa-play").addClass("fa-pause");P=!0;awpMediaPlay(w,D,m.getCounter())});g.on("pause",function(){g.isPlaying()||(Ab(),P=!1,awpMediaPause(w,D,m.getCounter()))});g.on("seek",function(a){ha&&Db.width(U.width()*a)});g.on("ready",function(){g.setVolume(z);var a=q.start||0;if(q.end)var b=q.end;q.playbackRate&&g.setPlaybackRate(q.playbackRate);da&&(b?g.play(a,b):g.play(a));da=!0});g.on("waveform_ME_noPeaks",function(){if(Va){var a=g.backend.getPeaks(900);
a.length&&n(a,q.peakName||q.title);Va=!1}wa.css("opacity",0);Ma.removeClass("awp-hidden").addClass("awp-visible");Ga()});g.on("redraw",function(){Fa&&(wa.css("opacity",0),Ma.removeClass("awp-hidden").addClass("awp-visible"),Ga(),Fa=!1)});this.getTitleFormatted=function(a,b){var c="",d=b||Cb;"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===
typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(c=a.artist):c=a.title:c=a.artist+d+a.title;return c};Vb.resize(function(){if(!k)return!1;ib&&clearTimeout(ib);ib=setTimeout(w.resize,150);ha&&na.width(U.width())});w.resize=function(){g&&(g.drawer.containerWidth=g.drawer.container.clientWidth,g.drawBuffer(),P||g.drawer.updateProgress(g.backend.getPlayedPercents()))};this.loadPlayMedia=function(){if(!k||!K||!q)return!1;N&&g.backend.peaks&&g.load(N,g.backend.peaks,!0);P=!0};
this.playMedia=function(){if(!k||!K||P)return!1;"undefined"!==typeof g&&g.play();P=!0};this.pauseMedia=function(){if(!k||!K||!P)return!1;"undefined"!==typeof g&&g.pause();P=!1};this.checkMedia=function(a){if(!k||!K)return!1;a=a.toLowerCase();P&&"pause"==a&&("undefined"!==typeof g&&g.pause(),P=!1)};this.togglePlayback=function(){if(!k||!K)return!1;"undefined"!==typeof g&&(!Na&&Ua&&g.backend.peaks?(da=!0,w.loadPlayMedia()):g.playPause())};this.stop=function(){if(!k||!K)return!1;"undefined"!==typeof g&&
g.stop();P=!1};this.nextMedia=function(){if(!k||!O)return!1;m.advanceHandler(1,!0)};this.previousMedia=function(){if(!k||!O)return!1;m.advanceHandler(-1,!0)};this.loadMedia=function(a,b){if(!k||X||!O)return!1;if("title"==a){var c;for(c=0;c<B;c++)if(b==H[c].data.title){b=c;var d=!0;break}if(!d)return alert('Track with title "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("counter"==a){if(0>b||b>B-1)return alert('Invalid track number. Track number  "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("id"==
a&&(c=E.find(".awp-playlist-item[data-media-id="+b+"]"),b=E.children(".awp-playlist-item").index(c),void 0==b||!b||-1==b))return alert("No media with ID to load! LoadMedia failed."),!1;m.processPlaylistRequest(b)};this.loadPlaylist=function(a){if(!k||X)return!1;if("undefined"===typeof a||AWPUtils.isEmpty(a))return alert("loadPlaylist method requires id parameter. loadPlaylist failed."),!1;if(ra==a)return!1;ra=a;y(ra)};this.addTrack=function(a,b,d,g){if(!k||X)return!1;if("undefined"===typeof a)return alert("addTrack method requires format parameter. AddTrack failed."),
!1;if("undefined"===typeof b)return alert("addTrack method requires track parameter. AddTrack failed."),!1;ya=!1;"undefined"!==typeof d&&(ya=d);d=1;var e=!1;if("string"!==typeof b&&"[object Object]"!==Object.prototype.toString.call(b))if("[object Array]"===Object.prototype.toString.call(b))d=b.length,e=!0;else return alert("addTrack method requires track as string, object or array parameter. AddTrack failed."),!1;L=g;pa=!1;ca=!0;if(O)if("undefined"!==typeof L){if(0>L||L>B)return alert('Invalid position to insert track to. Position number "'+
g+'" doesnt exist. AddTrack failed.'),!1;L==B&&(pa=!0)}else pa=!0,L=B;else{if("undefined"!==typeof L){if(0!=L)return alert('Invalid position to insert track to. Position number "'+g+'" doesnt exist. AddTrack failed.'),!1}else L=0;pa=!0}X=!0;nb();Ia=!1;$a=!0;oa=-1;Y=[];ba=[];for(g=0;g<d;g++){var f=e?b[g]:b;if("html"==a){f=c(f);var l=c("<div>").append(f.clone()).html();f=document.createElement("div");f.innerHTML=l;f=c(f.firstChild);f=J(f)}ba.push(f)}B=ba.length;xa=!1;O||(xa=!0);O=E;h()};this.inputAudio=
function(a){if(!k||X)return!1;if("undefined"===typeof a)return alert("inputAudio method requires data parameter. inputAudio failed."),!1;F();m.reSetCounter();q=a;K="audio";void 0!=q.title&&gb(w.getTitleFormatted(q));qa&&(da=!0);G()};this.removeTrack=function(a){if(!k||X||!O)return!1;if("undefined"===typeof a)return alert("removeTrack method requires id parameter. removeTrack failed."),!1;if("string"===typeof a){var b,c=!1;for(b=0;b<B;b++)if(a==H[b].data.title){a=b;c=!0;break}if(!c)return alert('Track with title "'+
a+'" doesnt exist. RemoveTrack failed.'),!1}else if("number"===typeof a){if(a=parseInt(a,10),0>a||a>B-1)return alert('Invalid id number. Track number  "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else return alert("removeTrack method requires either a id number or a track title to remove. removeTrack failed."),!1;H[a]?(E.children(".awp-playlist-item").eq(a).remove(),H.splice(a,1),Qa(),0<B?(b=m.getCounter(),a==b?(La(),m.setPlaylistItems(B)):(m.setPlaylistItems(B,!1),a<b&&m.reSetCounter(m.getCounter()-
1)),-1!=m.getCounter()?(Z=m.getCounter(),gb(Z)):awpMediaEmpty(w,D)):Xa()):alert('RemoveTrack with id "'+a+'" failed.')};this.sort=function(a,b){if(!k||!O)return!1;if("undefined"===typeof a)return console.log("Sort method requires type parameter. Sort method failed."),!1;var d=E.children("div.awp-playlist-item"),e=d.length,f=a.toLowerCase();if(2>e)return!1;if("title"==f)for(AWPUtils.keysrt2(H,"data","title_full",b||!1),e=[],f=0;f<B;f++)e.push(H[f].id);else if("random"==f)e=AWPUtils.randomiseArray(e),
H=AWPUtils.sortArray(H,e);else return console.log("Sort method requires type parameter. Sort method failed."),!1;f=m.getCounter();E.append(c.map(e,function(a){return d[a]}));-1!=f&&(e=E.children("div.awp-playlist-item[data-id='"+f+"']").index(),m.reSetCounter(e),Z=e);Qa()};this.destroyMedia=function(){if(!k)return!1;yb()};this.destroyPlaylist=function(){if(!k||!O)return!1;Xa()};this.destroyPlugin=function(){if(!k)return!1;yb();"undefined"!==typeof g&&g.destroy()};this.setPlaybackRate=function(a){if(!k||
"undefined"!==typeof m&&-1==m.getCounter())return!1;"undefined"!==typeof g&&g.setPlaybackRate(a)};this.toggleRandom=function(a){if(!k||"undefined"===typeof m)return!1;T="undefined"!==typeof a?a:!T;m.setRandom(T);T?la.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):la.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};this.toggleLoop=function(a){if(!k||"undefined"===typeof m)return!1;S="undefined"!==typeof a?a:!S;m.setLooping(S);S?ka.find("i").removeClass("awp-icon-color").addClass("awp-icon-rollover-color"):
ka.find("i").removeClass("awp-icon-rollover-color").addClass("awp-icon-color")};this.setVolume=function(a){if(!k)return!1;0>a?a=0:1<a&&(a=1);z=a;f()};this.getVolume=function(){return k?z:!1};this.toggleMute=function(){if(!k)return!1;a()};this.seek=function(a){if(!k||!K)return!1;"undefined"!==typeof g&&g.seekTo(a/g.getDuration())};this.getCurrentTime=function(){if(!k||!K)return!1;var a;"undefined"!==typeof g&&(a=g.getCurrentTime());return a};this.getDuration=function(){if(!k||!K)return!1;var a;"undefined"!==
typeof g&&(a=g.getDuration());return a};this.initPlaylistScroll=function(a){if(!k)return!1;kb(a)};this.destroyPlaylistScroll=function(){if(!k)return!1;fa.mCustomScrollbar("destroy");Ka=!1};this.updatePlaylistScroll=function(){if(!k)return!1;fa.mCustomScrollbar("update")};this.setAutoPlay=function(a){if(!k)return!1;da=a};this.getSetupDone=function(){return k};this.getPlaylistTransition=function(){return X};this.getPlaylistLoaded=function(){return Ia};this.getMediaPlaying=function(){return k?P:!1};
this.getActiveItemId=function(){return k?"undefined"!==typeof m?m.getCounter():null:!1};this.getPlaylistLength=function(){return k?AWPUtils.isNumber(B)?B:0:!1};this.getPlaylistItems=function(){if(!k)return!1;var a=[];E.find("div.awp-playlist-item").each(function(){a.push(c(this))});return a};this.getPlaylistData=function(){return H||null};this.getCurrMediaData=function(){return k?q:!1};this.getTitle=function(a){return va(a)};this.getSettings=function(){return k?u||null:!1};this.getInstanceName=function(){return k?
D:!1};this.toggleInteraction=function(){"undefined"!==typeof g&&g.toggleInteraction()};this.overControls=function(a){I(a)};this.outControls=function(a){p(a)};this.showPlayerElements2=function(){showPlayerElements2()};AWPUtils.isEmpty(ra)?tb():y(ra);return this}})(jQuery);