function awpSetupDone(instance,instanceName){var isIE=AWPUtils.isIE(),settings=instance.getSettings();if(instanceName=='fixed_bottom3'||instanceName=='wall2'){instance.find('.awp-info-toggle').on('click',function(e){instance.find('.awp-info-bar').toggle()}).on('mouseenter',function(e){instance.overControls(e)}).on('mouseleave',function(e){instance.outControls(e)});instance.find('.awp-info-close').on('click',function(e){instance.find('.awp-info-bar').hide()}).on('mouseenter',function(e){instance.overControls(e)}).on('mouseleave',function(e){instance.outControls(e)});instance.find('.awp-playlist-toggle').on('click',function(e){if(instance.find('.awp-playlist-holder').is(':visible')){instance.find('.awp-playlist-holder').hide()}else{instance.find('.awp-playlist-holder').show()}})}else if(instanceName=='poster'){instance.find('.awp-share-toggle').on('mouseenter',function(e){instance.find('.awp-share-holder').show()}).on('mouseleave',function(e){if(!isIE){instance.find('.awp-share-holder').hide()}else{var rt=e.toElement||e.relatedTarget;if(jQuery(rt).hasClass('awp-tooltip')||jQuery(rt).hasClass('awp-tooltip-inner'))return;instance.find('.awp-share-holder').hide()}})}}
function awpPlaylistEnd(instance,instanceName){}
function awpMediaStart(instance,instanceName,counter){}
function awpMediaPlay(instance,instanceName,counter){if(typeof awp_mediaArr!=undefined&&awp_mediaArr.length&&awp_mediaArr.length>1){var i,len=awp_mediaArr.length;for(i=0;i<len;i++){if(instance!=awp_mediaArr[i].inst){awp_mediaArr[i].inst.checkMedia('pause')}}}}
function awpMediaPause(instance,instanceName,counter){}
function awpMediaEnd(instance,instanceName,counter){}
function awpPlaylistStartLoad(instance,instanceName){}
function awpPlaylistEndLoad(instance,instanceName,playlistContent){var settings=instance.getSettings(),sourcePath=settings.sourcePath;if(instanceName=='wall2'||instanceName=='wall4'){if(instanceName=='wall2'){playlistItems=instance.getPlaylistItems();playlistLength=instance.getPlaylistLength();playlistContent.masonry('destroy');var grid=playlistContent.masonry({itemSelector:'.awp-playlist-item',columnWidth:'.awp-grid-sizer'});grid.imagesLoaded(function(){if(typeof doneResizing!=='undefined')doneResizing();grid.masonry('layout')}).progress(function(){grid.masonry('layout')});playlistContent.find('.awp-playlist-non-selected, .awp-playlist-selected').each(function(){var item=$(this);if(item.find('.awp-wall-preview').length==0){item.find('.awp-playlist-thumb').after(jQuery('<div class="awp-wall-preview"/>'))}
if(item.find('.awp-wall-overlay').length==0){item.find('.awp-playlist-thumb').after(jQuery('<div class="awp-wall-overlay"></div>'))}})}else if(instanceName=='wall4'){playlistContent.find('.awp-playlist-non-selected, .awp-playlist-selected').each(function(){var item=$(this);if(item.find('.awp-wall-overlay').length==0){item.find('.awp-playlist-thumb').after(jQuery('<div class="awp-wall-overlay"></div>'))}})}}}
function awpItemTriggered(instance,instanceName,counter){var data=instance.getPlaylistData()[counter].data;if(instanceName=='default'||instanceName=='default2'||instanceName=='default3'||instanceName=='default4'||instanceName=='poster'||instanceName=='multi1'||instanceName=='multi2'){var playerThumb=instance.find('.awp-player-thumb'),thumb=data.thumb||data.thumbDefault;if(playerThumb.length&&typeof thumb!=='undefined'){var img=new Image();img.className="awp-hidden";img.onload=function(){this.className="awp-visible"}
img.src=thumb;playerThumb[0].appendChild(img)}
if(instanceName=='default3'||instanceName=='poster'){instance.find('.awp-player-title').html(data.title);instance.find('.awp-player-artist').html(data.artist)}}else if(instanceName=='fixed_bottom3'||instanceName=='wall2'){instance.find('.awp-player-title').html(instance.getTitle(instance.getActiveItemId()));if(data.description&&!AWPUtils.isEmpty(data.description))instance.find('.awp-player-desc').html(data.description)}}
function awpPlaylistItemEnabled(instance,instanceName,item,id){if(instanceName=='wall2'||instanceName=='wall4'){item.removeClass('awp-active')}}
function awpPlaylistItemDisabled(instance,instanceName,item,id){if(instanceName=='wall2'||instanceName=='wall4'){item.addClass('awp-active')}}
function awpPlaylistItemClick(instance,instanceName,target,counter){}
function awpPlaylistItemRollover(instance,instanceName,target,id){}
function awpPlaylistItemRollout(instance,instanceName,target,id,active){}
function awpMediaEmpty(instance,instanceName){}
function awpPlaylistEmpty(instance,instanceName,playlistContent){}
function awpCleanMedia(instance,instanceName){}
function awpDestroyPlaylist(instance,instanceName,playlistContent){if(instanceName=='wall2'){playlistContent.masonry('destroy')}}
function awpVolumeChange(instance,instanceName,volume){}
function awpFilterChange(instance,instanceName,playlistContent){if(instanceName=='wall2'){playlistContent.masonry('layout')}}